# Generated by Django 4.1 on 2023-03-15 04:58

from django.db import migrations, models
import fontawesome_5.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
    ]
