# Generated by Django 4.1 on 2023-03-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_servicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pst_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pst_title',
            field=models.CharField(max_length=250, verbose_name='Post Title'),
        ),
    ]
